[package]
edition = '2018'
name = "cargo-crev"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[[bin]]
name = "cargo-crev"
path = "src/main.rs"

[dependencies]
failure = "*"
quicli = "*"
rpassword = "*"
rprompt = "*"
structopt = "*"
common_failures = "*"
crev-lib = { path = "../crev-lib" }
crev-data = { path = "../crev-data" }
crev-common = { path = "../crev-common" }
