[package]
edition = '2018'
name = "cargo-crev"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[[bin]]
name = "cargo-crev"
path = "src/main.rs"

[dependencies]
failure = "0.1"
quicli = "0.3"
structopt = "0.2"
common_failures = "0.1"
cargo = "0.31"
cargo-clone = { git = "https://github.com/dpc/cargo-clone" }
crev-lib = { path = "../crev-lib" }
crev-data = { path = "../crev-data" }
crev-common = { path = "../crev-common" }
crev-recursive-digest = { path = "../recursive-digest" }
semver = "0.9"
default = "0.1"
