[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
name = "crev"
version = "0.1.0"
[dependencies]
argonautica = "*"
base64 = "0.9.0"
blake2 = "*"
chrono = "*"
common_failures = "*"
ed25519-dalek = "*"
failure = "*"
hex = "*"
miscreant = "0.4.0-beta2"
nom = "*"
rand = "*"
serde = "1"
serde_derive = "1"
serde_yaml = "0.7"
