[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
name = "crev"
version = "0.1.0"
description = "Scalable, social, Code REView system that we desperately need"
keywords = ["code", "review", "tool", "distributed" ]
license = "MPL-2.0"
documentation = "https://docs.rs/crev"
homepage = "https://github.com/dpc/crev"
repository = "https://github.com/dpc/crev"
readme = "README.md"

[dependencies]
app_dirs = "*"
base64 = "0.9.0"
blake2 = "*"
chrono = "*"
common_failures = "*"
derive_builder = "*"
ed25519-dalek = "*"
failure = "*"
file = "*"
git2 = "*"
hex = "*"
miscreant = "0.4.0-beta2"
nom = "*"
quicli = "*"
rand = "*"
rpassword = "*"
rprompt = "*"
serde = "1"
serde_cbor = "*"
serde_derive = "1"
serde_yaml = "0.8"
structopt = "*"

[dependencies.argonautica]
features = ["serde"]
version = "0.1"
