[package]
name = "crev-lib"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Scalable, social, Code REView system that we desperately need"
documentation = "https://docs.rs/crev"
homepage = "https://github.com/dpc/crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/dpc/crev"
version = "0.0.1"

[dependencies]
crev-common = { path = "../crev-common" }
crev-data = { path = "../crev-data" }
app_dirs = "*"
common_failures = "*"
derive_builder = "*"
failure = "*"
chrono = "*"
base64 = "*"
git2 = "*"
hex = "*"
miscreant = "0.4.0-beta2"
rand = "0.5.5"
serde = "1"
serde_cbor = "*"
serde_derive = "1"
serde_yaml = "0.8"
tempdir = "*"
walkdir = "*"

[dependencies.argonautica]
features = ["serde"]
version = "0.1"
