[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Scalable, social, Code REView system that we desperately need - abstract data library"
documentation = "https://docs.rs/crev"
homepage = "https://github.com/dpc/crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0"
name = "crev-data"
readme = "README.md"
repository = "https://github.com/dpc/crev"
version = "0.0.1"

[dependencies]
crev-common = { path = "../crev-common" }
base64 = "0.9.0"
blake2 = "*"
chrono = "*"
common_failures = "*"
miscreant = "0.4.0-beta2"
ed25519-dalek = "*"
failure = "*"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
hex = "*"
rand = "*"
derive_builder = "*"

[dependencies.argonautica]
features = ["serde"]
version = "0.1"
