[package]
name = "crev-recursive-digest"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"

[dependencies]
walkdir = "2"
blake2 = "0.8"
digest = "0.8"
generic-array = "0.12"

[dev-dependencies]
tempdir = "*"
hex = "0.3"
