[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"
name = "crev-common"
version = "0.1.0"

[dependencies]
base64 = "0.10"
blake2 = "0.8"
chrono = "0.4"
hex = "0.3"
rprompt = "1"
rpassword = "2"
serde = "1"
serde_yaml = "0.8"
